###
# Copyright (2016-2020) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- hosts: all
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"
    cluster_profile_name: 'Test-1'
  tasks:
    - name: Create a Hypervisor Cluster Profile
      oneview_hypervisor_cluster_profile:
        config: "{{ config }}"
        state: present
        data:
          type: "HypervisorClusterProfileV3"
          name: "{{ cluster_profile_name }}"
          hypervisorManagerUri: '/rest/hypervisor-managers/ee73af7a-1775-44ba-8a66-d0479ec85678'
          path: 'DC1'
          hypervisorType: 'Vmware'
          hypervisorHostProfileTemplate:
            serverProfileTemplateUri: '/rest/server-profile-templates/f8e56c43-cfd7-436c-9812-394ecdbd32ed'
            hostprefix: 'Test-cluster-host'
      delegate_to: localhost
      register: hyp_cp

    - name: Do nothing with the Hypervisor Cluster Profile when no changes are provided
      oneview_hypervisor_cluster_profile:
        config: "{{ config }}"
        state: present
        data:
          name: "{{ cluster_profile_name }}"
          hypervisorManagerUri: '/rest/hypervisor-managers/ee73af7a-1775-44ba-8a66-d0479ec85678'
          path: 'DC1'
          hypervisorType: 'Vmware'
      delegate_to: localhost

    - name: Update the Hypervisor Cluster Profile changing the attribute name
      oneview_hypervisor_cluster_profile:
        config: "{{ config }}"
        state: present
        data:
          name: "{{ cluster_profile_name }}"
          newName: "HCP-renamed"
          hypervisorManagerUri: '/rest/hypervisor-managers/ee73af7a-1775-44ba-8a66-d0479ec85678'
          path: 'DC1'
          hypervisorType: 'Vmware'
      delegate_to: localhost
      register: hyp_cp

    - name: Delete the Hypervisor Cluster Profile
      oneview_hypervisor_cluster_profile:
        config: "{{ config }}"
        state: absent
        params:
          force: True
        data: "{{ hyp_cp.ansible_facts.hypervisor_cluster_profile }}"
      delegate_to: localhost
      register: deleted

    - name: Do nothing when Hypervisor Cluster Profile is absent
      oneview_hypervisor_cluster_profile:
        config: "{{ config }}"
        state: absent
        data: "{{ hyp_cp.ansible_facts.hypervisor_cluster_profile }}"
      delegate_to: localhost
      register: deleted
